import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

import SideNav from "./components/SideNav";
import "./globals.css";

const noto_sans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={noto_sans.className}>
      <body className="container mx-auto flex bg-background-950 text-text-50">
        <SideNav />
        <main className="bg-slate-700 min-h-screen w-3/4 space-y-4 overflow-auto py-6">
          {children}
        </main>
      </body>
    </html>
  );
}
