import type { Metadata } from "next";
import "./globals.css";
import { Noto_Serif } from "next/font/google";
import Link from "next/link";

const noto_sans = Noto_Serif({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={noto_sans.className}>
      <body className="bg-background-950 flex">
        <nav className="bg-background-900 border-r-accent-300 basis-1/4 border-r-4 px-8 py-4">
          <h1>RAWpertoire</h1>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/cv">CV</Link>
            </li>
            <li>
              <Link href="/current">Current Work</Link>
            </li>
          </ul>
        </nav>
        <main className="min-h-screen basis-3/4 space-y-4 overflow-auto bg-slate-700 py-6">
          {children}
        </main>
      </body>
    </html>
  );
}
