import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

import SideNav from "./components/SideNav";
import "./globals.css";

const noto_sans = Noto_Sans({
  subsets: ["latin"],
  weight: ["300", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={noto_sans.className}>
      <body className="bg-background-950 text-text-50 md:mx-auto md:flex md:min-h-screen md:p-4">
        <SideNav />
        <main className="bg-slate-700 flex space-y-4 overflow-auto py-6 lg:w-5/6">
          {children}
        </main>
      </body>
    </html>
  );
}
